- name: redis
  hosts: redis
  become: yes
  tasks:
    - name: run commands
      ansible.buildin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y;dnf module enable redis:remi-6.2 -y
    - name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present
    - name: allow all remote connections
      ansible.builtin.replace:
      path: /etc/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'    
    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes    